# Generated by Django 5.2 on 2025-05-06 14:52

import datetime
import django.db.models.deletion
import gestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('log', models.ImageField(blank=True, help_text='Select file to upload', upload_to=gestion.models.upload_logo, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='', max_length=20, verbose_name='PIN')),
                ('dni', models.CharField(default='', max_length=20, verbose_name='DNI')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Razón Social')),
                ('phone', models.CharField(default='0000000000', max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(default='', max_length=254, null=True, verbose_name='Email de contacto')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.company', verbose_name='Empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='', max_length=20, verbose_name='PIN')),
                ('dni', models.CharField(default='', max_length=20, verbose_name='DNI')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Razón Social')),
                ('phone', models.CharField(default='0000000000', max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(default='', max_length=254, null=True, verbose_name='Email de contacto')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.company', verbose_name='Empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False, verbose_name='Terminada')),
                ('ini_date', models.DateTimeField(default=datetime.datetime(2025, 5, 6, 14, 52, 48, 692068), null=True, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 5, 6, 14, 52, 48, 692094), null=True, verbose_name='Fin')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='gestion.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
