# Generated by Django 5.2 on 2025-05-07 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='log',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='workday',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 7, 59, 16, 260633), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 7, 59, 16, 260593), null=True, verbose_name='Inicio'),
        ),
    ]
