# Generated by Django 5.2 on 2025-05-07 12:25

import datetime
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_log_company_logo_alter_workday_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='qr',
            field=models.ImageField(blank=True, help_text='Select file to upload', upload_to=gestion.models.upload_qr, verbose_name='QR'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 12, 25, 6, 354962), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 12, 25, 6, 354934), null=True, verbose_name='Inicio'),
        ),
    ]
